improve building map tools
open-rmf/rmf_traffic_editor pull request #359
Opened 2021-06-10 05:32 UTC by nicholas-gs

## New feature implementation

### Implemented feature

1. Try to make model downloading more transparent during the package build process
2. Add functionality to filter models based on the availability of it in certain locations
3. Use Ignition fuel tools for downloading models for both classic gazebo and ignition gazebo instead of GET requests

### Implementation description

1. Just added some additional logging statements. Transparency is difficult during build process as colcon build by default only prints outputs after a package has been build, unless explicit told [otherwise](https://colcon.readthedocs.io/en/released/reference/event-handler-arguments.html).
2. `-i` flag in `building_map_model_downloader.py` to specify which folder to look for models first.
3. `-f` flag in `building_map_model_downloader.py` to specify to use Ignition fuel tool to download models.
3.1 Models are downloaded to `~/.ignition/fuel/fuel.ignitionrobotics.org/`
3.2 If `-e` flag is specified, then the downloaded models will be exported to the specified directory with the classic gazebo directory structure.

2021-06-11 04:44 UTC, aaronchongth requested changes
This is awesome, thanks for the amazing work, @nicholas-gs! Other than the few nitpicks here and there, I've found that the current implementation doesn't deal well with model names that have spaces in them. This is the log for building `rmf_demos_map`, specifically for models `pine tree`, `oak tree`, `standing person`, `lamp post`, etc

```bash
[Err] [FuelClient.cc:655] Failed to download model.
  Server: https://fuel.ignitionrobotics.org
  Route: openrobotics/models/oak/tip/oak.zip
  REST response code: 404
[Err] [FuelClient.cc:655] Failed to download model.
  Server: https://fuel.ignitionrobotics.org
  Route: openrobotics/models/standing/tip/standing.zip
  REST response code: 404
[Err] [FuelClient.cc:655] Failed to download model.
  Server: https://fuel.ignitionrobotics.org
  Route: openrobotics/models/construction/tip/construction.zip
  REST response code: 404
[Err] [FuelClient.cc:655] Failed to download model.
  Server: https://fuel.ignitionrobotics.org
  Route: openrobotics/models/oak/tip/oak.zip
  REST response code: 404
[Err] [FuelClient.cc:655] Failed to download model.
  Server: https://fuel.ignitionrobotics.org
  Route: openrobotics/models/oak/tip/oak.zip
  REST response code: 404
[Err] [FuelClient.cc:655] Failed to download model.
  Server: https://fuel.ignitionrobotics.org
  Route: openrobotics/models/pine/tip/pine.zip
  REST response code: 404
[Err] [FuelClient.cc:655] Failed to download model.
  Server: https://fuel.ignitionrobotics.org
  Route: openrobotics/models/lamp/tip/lamp.zip
  REST response code: 404
[Err] [FuelClient.cc:655] Failed to download model.
  Server: https://fuel.ignitionrobotics.org
  Route: openrobotics/models/pine/tip/pine.zip
  REST response code: 404
[Err] [FuelClient.cc:655] Failed to download model.
  Server: https://fuel.ignitionrobotics.org
  Route: openrobotics/models/pine/tip/pine.zip
  REST response code: 404
```

Once these have been resolved, would you say that it would be a drop-in replacement for the `http` way of downloading models? If so, we can add a note that the `http` way of downloading models will be deprecated in the near future.

2021-06-11 04:44 UTC, aaronchongth commented on rmf_building_map_tools/pit_crew/pit_crew.py
> +from pprint import pprint
Looks like this is not used anymore

2021-06-11 04:44 UTC, aaronchongth commented on rmf_building_map_tools/pit_crew/pit_crew.py
> +import subprocess
Nit: can you bump this line up to near the top, since the import lines are sorted from long to short

2021-06-11 04:44 UTC, aaronchongth commented on rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py
> +    # Ignitional fuel tools can only download to this folder, so we set the
```suggestion
    # Ignition fuel tools can only download to this folder, so we set the
```

2021-06-11 08:43 UTC, nicholas-gs commented
Thank you Aaron for the comments. 

The issue with my first commit is that the url links need spaces to be encoded with `%20`. I've fixed the problem, but additionally I needed to rename the downloaded folders since fuel tools downloads the models to the folder `standing%20person` for example.

I'm not too sure if this would be a drop-in replacement for the http way of downloading models due to being unable to specify the download folder? Fuel tools can only seem to download to `~/.ignition/fuel/fuel.ignitionrobotics.org/`.

2021-06-21 04:51 UTC, aaronchongth commented
Hey @nicholas-gs, sorry for the delayed review.

| I'm not too sure if this would be a drop-in replacement for the http way of downloading models due to being unable to specify the download folder? Fuel tools can only seem to download to ~/.ignition/fuel/fuel.ignitionrobotics.org/.

Wouldn't these lines copy it to the desired folder after downloading them to `~/.ignition/fuel/fuel.ignitionrobotics.org`?

2021-06-21 06:23 UTC, nicholas-gs commented
Yes you are right. Its probably a non-issue.

2021-06-21 06:49 UTC, aaronchongth approved these changes
LGTM!

2021-06-21 06:49 UTC, merged